// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"github.com/audunhov/tombolig/models"
)

func Home(username string, stats models.Stats) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"max-w-7xl mx-auto px-4 sm:px-6 bg-gray-50 lg:px-8 min-h-full\"><header class=\"flex justify-between items-center py-6 border-b border-gray-100\"><a href=\"/\" class=\"flex h-10 w-10 shrink-0 shadow-md shadow-blue-200 hover:scale-105 transition-all active:scale-95\" title=\"Gå til forsiden\"><img src=\"/static/img/logo.svg\" alt=\"Boligaksjonen Logo\" class=\"h-full w-full rounded-xl\"></a></header><main class=\"py-16 lg:py-24\"><div class=\"max-w-4xl mx-auto text-center mb-20\"><h1 class=\"text-5xl lg:text-8xl font-black text-gray-900 leading-[0.9] tracking-tighter mb-8 text-balance\">Det står <span class=\"text-blue-600 whitespace-nowrap\">200 000</span> boliger tomme i Norge.</h1><p class=\"text-xl lg:text-2xl text-gray-500 font-medium leading-relaxed mb-12 max-w-2xl mx-auto\">Samtidig som boligprisene skyter i været, står tusenvis av hjem og forfaller. Hjelp oss med å kartlegge dem.</p><div class=\"flex flex-col sm:flex-row gap-4 justify-center\"><a href=\"/kart\" class=\"px-10 py-5 bg-gray-900 hover:bg-black text-white text-lg font-black uppercase tracking-widest rounded-2xl shadow-2xl transition-all scale-100 hover:scale-105 active:scale-95\">Utforsk kartet nå</a></div></div><!-- Stats Grid --><div class=\"grid grid-cols-1 md:grid-cols-2 gap-8 mb-32 max-w-4xl mx-auto\"><div class=\"bg-white p-10 rounded-[2.5rem] shadow-xl shadow-gray-200/50 border border-gray-100 text-center\"><p class=\"text-[10px] font-black uppercase tracking-[0.2em] text-gray-400 mb-2\">Kartlagte boliger</p><p class=\"text-6xl font-black text-blue-600 tracking-tighter\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", stats.TotalHouses))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/home.templ`, Line: 37, Col: 106}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</p></div><div class=\"bg-white p-10 rounded-[2.5rem] shadow-xl shadow-gray-200/50 border border-gray-100 text-center\"><p class=\"text-[10px] font-black uppercase tracking-[0.2em] text-gray-400 mb-2\">Bidragsytere</p><p class=\"text-6xl font-black text-gray-900 tracking-tighter\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", stats.TotalContributors))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/home.templ`, Line: 41, Col: 112}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</p></div></div><div class=\"max-w-5xl mx-auto bg-white p-8 lg:p-16 rounded-[3rem] shadow-2xl shadow-gray-200/50 border border-gray-100 relative overflow-hidden text-balance\"><div class=\"absolute top-0 right-0 p-8 hidden lg:block\"><svg class=\"size-64\" viewBox=\"0 0 24 24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M12 2C8.13 2 5 5.13 5 9C5 14.25 12 22 12 22C12 22 19 14.25 19 9C19 5.13 15.87 2 12 2Z\" fill=\"#2563EB\"></path> <circle cx=\"12\" cy=\"9\" r=\"2.5\" fill=\"#1E40AF\"></circle></svg></div><div class=\"relative z-10 lg:w-2/3\"><h2 class=\"text-3xl lg:text-5xl font-black text-gray-900 tracking-tight mb-6 italic\">Hvorfor gjør vi dette?</h2><p class=\"text-lg text-gray-600 mb-8 leading-relaxed\">Ifølge en fersk rapport omtalt i <a href=\"https://e24.no/norsk-oekonomi/i/RjyKEW/ny-rapport-200-000-boliger-staar-tomme-i-norge\" target=\"_blank\" class=\"text-blue-600 font-bold hover:underline\">E24</a>, står det nesten 200 000 boliger tomme i Norge. Dette er boliger som kunne vært brukt til å løse boligkrisen, skape liv i distriktene eller gi unge en vei inn på markedet.</p><p class=\"text-lg text-gray-600 leading-relaxed\">Boligaksjonen er en åpen, samfunnsdrevet plattform for å kartlegge tomme boliger. Sammen bygger vi bevisbyrden for en mer rettferdig boligpolitikk.</p></div></div></main><footer class=\"py-12 border-t border-gray-100 text-center text-gray-400\"><a href=\"https://github.com/audunhov/boligaksjonen\" target=\"_blank\" class=\"hover:underline\">GitHub</a></footer></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Boligaksjonen", username).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
